- name: install nginx and run
  hosts: web
  tasks:
  - name: install nginx
    ansible.builtin.dnf:
    name: nginx
    state: latest
  - name: service start
    ansible.builtin.service:
    name: nginx
    state: started
    enabled: yes

