- name: conditions
  hosts: localhost
  vars_prompt:
  - name: NUMBER
  prompt: enter the 
  private: false
  tasks:
  - name: print the less than number
    ansible.builtin.debug:
      msg: "number is less than  {{NUMBER}}"
    when: number < 10 

  - name: print the greater than is equal to
    ansible.builtin.debug:
      msg: "number is greater than equal to {{NUMBER}}"
    when: number > 10