- name: conditions
  hosts: localhost
  vars_prompt:
    - name: number
      prompt: "Enter the number"
      private: false
  tasks:
    - name: print the less than number
      ansible.builtin.debug:
        msg: "Number is less than {{ number }}"
      when: number | int < 10
    - name: print the greater than or equal to number
      ansible.builtin.debug:
        msg: "Number is greater than or equal to {{ number }}"
      when: number | int >= 10
