# set the default value
- name: default value
  hosts: localhost
  tasks:
  - name: print the default value
    ansible.builtin.debug:
      msg: "course is {{couse | default ('ansible')}}"

# convert in to uppercase

- name: uppercase
  hosts: localhost
  vars:
    wishes: "happy birtday"
  tasks:
    - name: convert in to uppercase
      ansible.builtin.debug:
        msg: " today is srikanth {{wishes | upper}}"

# coverted into lowercase

- name: lowercase
  hosts: localhost
  vars:
    week: "today is sunday"
  tasks:
  - name: convert into lowercase
    ansible.builtin.debug:
      msg: "hii, {{week | lower}}"


# REMOVE DUPLICATES

- name: remove duplicates
  hosts: localhost
  vars:
    numbers: [1,2,2,2,3,3,3,4,4,5]
  tasks:
  - name: remove the duplicates
    ansible.builtin.debug:
      msg: "remove the extra dulicates in my list {{numbers | unique}}"
