# set the default value
- name: default value
  hosts: localhost
  tasks:
  - name: print the default value
    ansible.builtin.debug:
      msg: "course is {{couse | default ('ansible')}}"

# convert in to uppercase

- name: uppercase
  hosts: localhost
  vars:
    wishes: "happy birtday"
  tasks:
    - name: convert in to uppercase
      ansible.builtin.debug:
        msg: " today is srikanth {{wishes | upper}}"

# coverted into lowercase

- name: lowercase
  hosts: localhost
  vars:
    week: "today is sunday"
  tasks:
  - name: convert into lowercase
    ansible.builtin.debug:
      msg: "hii, {{week | lower}}"


# REMOVE DUPLICATES

- name: remove duplicates
  hosts: localhost
  vars:
    numbers: [1,2,2,2,3,3,3,4,4,5]
  tasks:
  - name: remove the duplicates
    ansible.builtin.debug:
      msg: "remove the extra dulicates in my list {{numbers | unique}}"

# print the min and max

- name: min and max
  hosts: localhost
  vars:
    ages: [45,65,87,76,54]
  tasks:
  - name: print the min and max
    ansible.builtin.debug:
      msg: "{min age is {{ages | min}} and max age is  {{ages | max}}"

# converted into dictionaty to items

- name: dictionaty to items
  hosts: localhost
  vars:
    my_dict: #this is dict/map/key=value
      movie: rrr
      heros: ntr and ramcharan
      ticket: 150
  tasks:
  - name: converted into dictionaty to items
    ansible.builtin.debug:
      msg: "panindia movie details is {{my_dict | dict2items}}"

# this is output of  dictionaty to items
#[{'key': 'movie', 'value': 'rrr'}, 
#{'key': 'heros', 'value': 'ntr and ramcharan'},
#{'key': 'ticket', 'value': 150}]"

# converted into items to dictinary

- name: converted into items to dictinary
  hosts: localhost
  vars:
  - {'key': 'movie', 'value': 'rrr'}
  - {'key': 'heros', 'value': 'ntr and ramcharan'}
  - {'key': 'ticket', 'value': 150}
  tasks:
  - name: converted into items to dictinary
    ansible.builtin.debug:
      msg: "{{items2dict}}"