- name: loops
  hosts: localhost
  tasks:
  - name: print the loops
    ansible.builtin.debug:
      msg: "hii, {{item}}"
    loop:
    - mysql
    - nodejs
    - python

- name: install the packages
  hosts: localhost
  tasks:
  - name: install packages
    ansible.builtin.debug:
      msg: "install the packages {{list}}"
    loop:
    - nodejs
    - mysql
    - nginx