- name: loops
  hosts: localhost
  tasks:
  - name: print the loops
    ansible.builtin.debug:
      msg: "hii, {{item}}"
    loop:
    - mysql
    - nodejs
    - python

- name: install the packages
  hosts: localhost
  become: yes
  tasks:
  - name: install packages
    ansible.builtin.dnf:
      name: "{{item}}"
      state: latest
    loop:
    - nodejs
    - mysql
    - nginx