- name: loops
  hosts: localhost
  tasks:
  - name: print the loops
    ansible.builtin.debug:
      msg: "hii, {{item}}"
    loop:
    - mysql
    - nodejs
    - python

- name: install the packages
  hosts: localhost
  become: yes
  tasks:
  - name: install packages
    ansible.builtin.dnf:
      name: "{{item}}"
      state: latest
    loop:
    - nodejs
    - mysql
    - nginx


- name: install and remove 
  hosts: localhost
  become: yes
  tasks:
  - name: install and remove
    ansible.builtin.dnf:
      name: "{{list.name}}"
      state: "{{list.state}}"
      state:
    loop:
    - { name: 'nodejs', state: 'latest' }
    - { name: 'mysql',  state: 'absent'}
    - { name: 'nginx',  state: 'absent'}
