- name: conditions
  hosts: web
  tasks:
  - name: check the user exists or not
    ansible.builtin.command: id expense
    register: user
    handle_error: true
  - name: check the user info
    ansible.builtin.debug:
      msg: "check the user info: {{user}}"