- name: datatypes
  hosts: localhost
  vars: #lists
    course: aws and devops
    tools:
      - lists
      - shell
      - ansible
    experience: #map or dicitonary
      devops: 3 # number
      aws: 1
      docker: 1
    realproject: true
  tasks:
  - name: print variables
    ansible.builtin.debug:
      msg: "course is {{course}} and tools is {{tools}} and experience is {{experience}} and {{realproject}}"
