- name: variables
  hosts: localhost
  vars:
    course: "terraform"
    trainer: "siva"
    duration: "120hr"
  tasks:
  - name: print override information
    vars:
      course: "devops"
    ansible.builtin.debug:
      msg: "hii this is srikanth  course is {{course}} and trainer is {{trainer}} and duration is {{duration}}"
  
  - name: print  information
    ansible.builtin.debug:
      msg: "hii this is srikanth  course is {{course}} and trainer is {{trainer}} and duration is {{duration}}"     