- name: variables from inventory
  hosts: localhost
  vars:
    timings: "7:30 ist"
  tasks:
  - name: print the information
    ansible.builtin.debug:
      msg: " this is srikanth course is {{course}} and trainer is {{trainer}} and duration is {{duration}} and {{timings}}"