- name: variable from files
  hosts: localhost
  vars_files:
  -vars.yaml
  tasks:
  - name: variables
    ansible.builtin.debug:
      msg: "movie name {{movie}} and director of the movie is {{director}} and  budget of movie is {{budget}}"